USE [master]
GO

/****** Object:  Database [MiAgendaDB]    Script Date: 25/09/2020 12:43:23 a. m. ******/
DROP DATABASE [MiAgendaDB]
GO

/****** Object:  Database [MiAgendaDB]    Script Date: 25/09/2020 12:43:23 a. m. ******/
CREATE DATABASE [MiAgendaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MiAgendaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MiAgendaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MiAgendaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MiAgendaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MiAgendaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MiAgendaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MiAgendaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MiAgendaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MiAgendaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MiAgendaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MiAgendaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MiAgendaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MiAgendaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MiAgendaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MiAgendaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MiAgendaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MiAgendaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MiAgendaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MiAgendaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MiAgendaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MiAgendaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MiAgendaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MiAgendaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MiAgendaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MiAgendaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MiAgendaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MiAgendaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MiAgendaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MiAgendaDB] SET  MULTI_USER 
GO

ALTER DATABASE [MiAgendaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MiAgendaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MiAgendaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MiAgendaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MiAgendaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MiAgendaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MiAgendaDB] SET  READ_WRITE 
GO

